services:
  - type: web
    name: ai-first-draft-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: OPENAI_API_KEY
        value: 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